spring.application.name=multiplex
spring.datasource.url=jdbc:h2:mem:multiplex
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
>>>>>>> 4ea1b8d603e5e44b5cc919ab15b520f1631cca28
